name: CI/CD

on:
  push:
    branches:
      - master  # 仅在推送到master分支时触发此工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的Ubuntu环境中运行

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 使用GitHub官方的checkout动作来检出代码

    - name: Set up JDK 21
      uses: actions/setup-java@v3  # 设置Java开发环境
      with:
        distribution: 'zulu'
        java-version: '21'  # 指定使用JDK 21版本

    - name: Build with Maven
      run: mvn clean package -DskipTests  # 使用Maven构建项目，并跳过测试以加快构建速度
      working-directory: backend/edu-agent   # 指定工作目录

    # 上传构建的JAR文件到远程服务器
    - name: Upload to remote server
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} rsync -avz -e "ssh -T -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" ./backend/edu-agent/target/edu-agent-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/ccc212/data1/ccc212/My/web/edu-agent/build/

    # 在远程服务器上执行命令
    - name: Execute remote commands
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -T -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/ccc212/data1/ccc212/My/web/edu-agent  # 切换到目标目录
          sh ./deploy.sh  # 执行部署脚本
        EOF
