name: CI/CD

on:
  push:
    branches:
      - master  # 仅在推送到master分支时触发此工作流

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # 在最新的Ubuntu环境中运行

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 使用GitHub官方的checkout动作来检出代码

    # --- 设置 JDK 8 用于 ccc212-code-sandbox 项目 ---
    - name: Set up JDK 8 for ccc212-code-sandbox
      uses: actions/setup-java@v3  # 设置Java开发环境
      with:
        distribution: 'zulu'
        java-version: '8'  # 指定使用JDK 8版本
        cache: 'maven' # 启用Maven缓存

    # --- 构建并部署 ccc212-code-sandbox 项目 ---
    - name: Build ccc212-code-sandbox with Maven
      run: mvn clean package -DskipTests  # 使用Maven构建项目，并跳过测试以加快构建速度
      working-directory: backend/ccc212-code-sandbox

    - name: Upload ccc212-code-sandbox to remote server
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} rsync -avz -e "ssh -T -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" \
        ./backend/ccc212-code-sandbox/target/ccc212-code-sandbox-0.0.1-SNAPSHOT.jar \
        ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/ccc212/data1/ccc212/My/web/ccc212-code-sandbox/build/

    - name: Execute remote commands for ccc212-code-sandbox
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -T -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/ccc212/data1/ccc212/My/web/ccc212-code-sandbox
          sh ./deploy.sh
        EOF

    # --- 设置 JDK 21 用于 edu-agent 项目 ---
    - name: Set up JDK 21 for edu-agent
      uses: actions/setup-java@v3  # 设置Java开发环境
      with:
        distribution: 'zulu'
        java-version: '21'  # 指定使用JDK 21版本
        cache: 'maven' # 启用Maven缓存

    # --- 构建并部署 edu-agent 项目 ---
    - name: Build edu-agent with Maven
      run: mvn clean package -DskipTests
      working-directory: backend/edu-agent # 指定 edu-agent 的工作目录

    - name: Upload edu-agent to remote server
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} rsync -avz -e "ssh -T -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" \
        ./backend/edu-agent/target/edu-agent-0.0.1-SNAPSHOT.jar \
        ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/ccc212/data1/ccc212/My/web/edu-agent/build/

    - name: Execute remote commands for edu-agent
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -T -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/ccc212/data1/ccc212/My/web/edu-agent  # 切换到 edu-agent 目标目录
          sh ./deploy.sh  # 执行 edu-agent 的部署脚本
        EOF
